version: "3"
services:
  app:
    container_name: lilreddit-app
    image: lilreddit-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file: .env.local
    depends_on:
      - db
    volumes: # For hot reload
      - ./:/app
      - /node_modules
      - /.next
    ports:
      - "3000:3000"
      - "9229:9229"
  db:
    container_name: lilreddit-db
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: lilreddit

