version: "3"
services:
  next:
    container_name: next-reddit
    image: nextjs-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    volumes: # For hot reload
      - ./:/app
      - /node_modules
      - /.next
    ports:
      - "3000:3000"
      - "9229:9229"
  postgres:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: lilreddit

