import { posts, queryClient } from '@/api';
import type { NextPage } from 'next';
import Head from 'next/head';
import { dehydrate, useQuery } from 'react-query';

export async function getServerSideProps() {
  await queryClient.prefetchQuery('posts', () => posts());

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

const Home: NextPage = () => {
  const { data } = useQuery(['posts'], () => posts());
  // const data = {d:"a"};
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && JSON.stringify(data)}
    </div>
  );
};

export default Home;
